---
# role: chronyd
# file: tasks/main.yml

- name: "CHRONYD | Load platform variables"
  ansible.builtin.include_vars: "{{ role_path }}/vars/{{ ansible_facts.os_family }}.yml"

- name: "CHRONYD | Remove conflicting packages"
  become: true
  become_user: root
  ansible.builtin.package:
    name: "{{ __chronyd_remove_packages }}"
    state: absent

- name: "CHRONYD | Install packages"
  become: true
  become_user: root
  ansible.builtin.package:
    name: "{{ __chronyd_packages }}"
    state: present

- name: "CHRONYD | Discover installed conflicting services"
  ansible.builtin.service_facts:
  when:
    - ansible_facts.service_mgr == 'systemd'
    - __chronyd_conflicting_services | length > 0

- name: "CHRONYD | Stop installed conflicting services"
  become: true
  become_user: root
  ansible.builtin.service:
    name: "{{ __chronyd_conflicting_service }}"
    enabled: false
    state: stopped
  loop: "{{ __chronyd_conflicting_services }}"
  loop_control:
    loop_var: __chronyd_conflicting_service
    label: "{{ __chronyd_conflicting_service }}"
  when:
    - ansible_facts.service_mgr == 'systemd'
    - (__chronyd_conflicting_service ~ '.service') in ansible_facts.services
    - ansible_facts.services[__chronyd_conflicting_service ~ '.service'].status != 'not-found'

- name: "CHRONYD | Mask conflicting systemd services"
  become: true
  become_user: root
  ansible.builtin.systemd_service:
    name: "{{ __chronyd_conflicting_service }}"
    masked: true
  loop: "{{ __chronyd_conflicting_services }}"
  loop_control:
    loop_var: __chronyd_conflicting_service
    label: "{{ __chronyd_conflicting_service }}"
  when: ansible_facts.service_mgr == 'systemd'

- name: "CHRONYD | Write configuration"
  become: true
  become_user: root
  ansible.builtin.template:
    src: etc/chrony.conf.j2
    dest: "{{ __chronyd_conf }}"
    owner: root
    group: root
    mode: "0644"
    backup: true
    validate: "{{ __chronyd_validate }}"
  notify: restart daemon

- name: "CHRONYD | Enable and start service"
  become: true
  become_user: root
  ansible.builtin.service:
    name: "{{ __chronyd_service }}"
    enabled: true
    state: started

- name: "CHRONYD | Apply configuration changes"
  ansible.builtin.meta: flush_handlers
